### ISSUE TITLE
Todo Fails to Work

### ISSUE THREAD

**Issue by madebyjeffrey** [fastmail/overture#15]
In Chrome, Firefox, and Safari (all latest versions, on mac), the Todo doesn't work and in the error console is:

[["getTodoLists",{},"0"],["getTodos",{},"1"]]
Overture-raw.js:4361 TypeError this.didFetchAll is not a function TypeError: this.didFetchAll is not a function
    at App.source.handle.todoLists (http://overturejs.com/examples/Todo/Todo.js:117:14)
    at NS.Class.receive (http://overturejs.com/build/Overture-raw.js:12791:29)
    at null.ioDidSucceed (http://overturejs.com/build/Overture-raw.js:12675:14)
    at NS.EventTarget.fire (http://overturejs.com/build/Overture-raw.js:3605:71)
    at null.<anonymous> (http://overturejs.com/build/Overture-raw.js:19992:16)
    at Object.RunLoop.invoke (http://overturejs.com/build/Overture-raw.js:4173:20)
    at null._xhrStateDidChange (http://overturejs.com/build/Overture-raw.js:4428:21)
    at xhr.onreadystatechange (http://overturejs.com/build/Overture-raw.js:19931:18)
    at XMLHttpRequest._returnResultForData (http://overturejs.com/examples/Todo/fixtures.js:149:10)
    at http://overturejs.com/examples/Todo/fixtures.js:115:14
Overture-raw.js:4361 TypeError this.didFetchAll is not a function TypeError: this.didFetchAll is not a function
    at App.source.handle.todos (http://overturejs.com/examples/Todo/Todo.js:173:14)
    at NS.Class.receive (http://overturejs.com/build/Overture-raw.js:12791:29)
    at null.ioDidSucceed (http://overturejs.com/build/Overture-raw.js:12675:14)
    at NS.EventTarget.fire (http://overturejs.com/build/Overture-raw.js:3605:71)
    at null.<anonymous> (http://overturejs.com/build/Overture-raw.js:19992:16)
    at Object.RunLoop.invoke (http://overturejs.com/build/Overture-raw.js:4173:20)
    at null._xhrStateDidChange (http://overturejs.com/build/Overture-raw.js:4428:21)
    at xhr.onreadystatechange (http://overturejs.com/build/Overture-raw.js:19931:18)
    at XMLHttpRequest._returnResultForData (http://overturejs.com/examples/Todo/fixtures.js:149:10)
    at http://overturejs.com/examples/Todo/fixtures.js:115:14

**Comment by neilj** [comment]
Ah yes, I forgot to update the Todo demo with the latest changes to the store API. Now fixed, thanks for reporting.
